### ISSUE TITLE
What if your hosts do not have docker installed

### ISSUE THREAD

**Issue by bgrissin** [clemenko/ucp#1]
Or even worse, they have a reel release that is two versions behind.  We have a repo that a uses a heat template that provisions OSP hosts with the latest CS release of docker engine

**Comment by clemenko** [comment]
CoreOS FTW!  Some places don't have Heat setup. OR the OS's you are allowed to use is limited.

**Comment by bgrissin** [comment]
not disagreeing with you, but RHT and Ubuntu are everywhere and the "only OS that matters"
to set up DOcker on each hypervisor, you only need cloud-init

**Comment by clemenko** [comment]
good point. So My script assumes CoreOS. But you could easily change the build function to use cloud-init and ANY os.

**Comment by bgrissin** [comment]
so am I putting in PRs now :)

**Comment by clemenko** [comment]
aw shucks!

**Comment by clemenko** [comment]
FYI, this is updated for digital ocean. I dropped supernova/openstack
